name: dependencies
on:
  push:
  pull_request:
  schedule:
    - cron: '0 21 * * *'
jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquidz/antq-action@v1
        with:
          excludes: 'clojure/brew-install'
